### ISSUE TITLE
Vault Plugin is taking ~60 seconds to start, this seems to lock Vault until startup is complete

### ISSUE THREAD

**Issue by GeoffVenafi** [Venafi/vault-pki-backend-venafi#62] opened 2020-09-09 23:51 UTC
**PROBLEM SUMMARY**
When the HashiCorp Vault plugin is starting up it can take up to 60 seconds to start. This is an issue as the Vault becomes locked during that time and no other vault requests can be handled. 

**STEPS TO REPRODUCE**
I do not have specific steps at this time as I am opening this for a customer. I will get this information and relay when I have it or the customer can update if possible. 

**EXPECTED RESULTS**
That the plugin will not prevent other vault requests while starting. 

**ACTUAL RESULTS**
While plugin is starting up the HashCorp Vault is locked and not able to handle any further requests until the plugin startup completes ~60 seconds. 

**ENVIRONMENT DETAILS**
Venafi TPP: 18.2.0
Venafi Vault Plugin: v0.6.4
HashiCorp Vault: unknown at this time

High Level architecture:
Vault HA cluster with a replicated HA cluster in a different location. 

**COMMENTS/WORKAROUNDS**
no known workaround at this time.

**Comment by tr1ck3r** [comment] 2020-09-10 00:41
General support for Trust Protection Platform 18.2 ended [1 July 2020](https://support.venafi.com/hc/en-us/articles/215912217).  While this Venafi Secrets Engine is believed to be backward compatible as far back as TPP 17.3 (based on the API calls it requires), it is expected for versions prior to 18.4 to under perform due to a major feature introduced in 18.4 (older versions checked for work every 60 seconds by default whereas 18.4 and higher process certificate requests as soon as there is an available worker).  Effectively, that means TPP versions prior to 18.4 are not viable for DevOps use cases like this.

The first release of this solution ([v0.3.1](https://github.com/Venafi/vault-pki-backend-venafi/releases/tag/0.3.1)) was developed and tested against TPP 18.4.  We've not observed any Vault locking behavior in our tests but it is expected to take up to 60 seconds before TPP 18.2 will start working on a certificate request submitted by this secrets engine.  As such I strongly recommend upgrading to latest version of TPP.

**Comment by tr1ck3r** [comment] 2020-09-18 20:10
HashiCorp Engineering has reproduced this issue and determined that it is caused by interactions between lazy-loading of a plugin due to rollback and the synchronous invalidation process that is triggered on every heartbeat (5 seconds) within the replication system.  They indicated it will be addressed in Vault 1.5.4 by eliminating the trigger of a sync invalidation call on every heartbeat unless strictly required.

**Comment by GeoffVenafi** [comment] 2020-09-18 20:16
Thanks for the update I will pass this along to the Venafi Team.

**Comment by tr1ck3r** [comment] 2020-09-30 16:07
@GeoffVenafi have you been able to verify that Vault 1.5.4 resolved this issue?  It was [released](https://discuss.hashicorp.com/t/ann-vault-1-5-4-released/14659) last week.

**Comment by tr1ck3r** [comment] 2020-10-21 18:41
Issue was a bug in Vault and was resolved in the v1.5.4 release.

**Closed by tr1ck3r** 2020-10-21 18:41 UTC
